=== Douzal/AFCEPF---DOSSIER-COMMUN/05 - XML/demo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 sp2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
 elementFormDefault="qualified">
	<xs:include schemaLocation="voiture.xsd"/>
	<xs:element name="numero" type="xs:string"/>
	<xs:element name="voie" type="xs:string"/>
	<xs:element name="ville" type="xs:string"/>
	<xs:element name="tauxInteret">
		<xs:complexType>
			<xs:attribute name="taux" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:enumeration value="0.05"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="solde" type="xs:short"/>
	<xs:element name="raisonSociale">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="afcepf"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="prenom">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="chauvet"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="nom">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="benoit"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="dateOuverture" type="xs:string"/>
	<xs:element name="compte">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="tauxInteret" minOccurs="0"/>
				<xs:element ref="solde"/>
				<xs:element ref="dateOuverture"/>
			</xs:sequence>
			<xs:attribute name="numero" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="codePostal" type="xs:int"/>
	<xs:element name="clients">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="client" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="client">
		<xs:complexType>
			<xs:sequence>
				<xs:choice>
					<xs:element ref="raisonSociale"/>
					<xs:sequence>
						<xs:element ref="nom"/>
						<xs:element ref="prenom"/>
					</xs:sequence>
				</xs:choice>
				<xs:element ref="compte" maxOccurs="unbounded"/>
				<xs:element ref="adresse"/>
				<xs:element ref="voiture"/>
			</xs:sequence>
			<xs:attribute name="sexe" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Masculin"/>
						<xs:enumeration value="FÃ©minin"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="perso"/>
						<xs:enumeration value="pro"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="numero" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="clt1"/>
						<xs:enumeration value="clt2"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="idAgence" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ag1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="banque">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="clients"/>
				<xs:element ref="agences"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="agences">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="agence"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="agence">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="adresse"/>
			</xs:sequence>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="ag1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="adresse">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="numero"/>
				<xs:element ref="voie"/>
				<xs:element ref="codePostal"/>
				<xs:element ref="ville"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Douzal/AFCEPF---DOSSIER-COMMUN/05 - XML/demoXSLT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ci dessus, le prologue -->
<!--<!DOCTYPE banque SYSTEM "demo.dtd">-->

<?xml-stylesheet type="text/xsl" href="demoCsv.xsl"?>

<banque xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="demo2.xsd" libelle="Banque de france">
	<clients>
		<client type="pro" sexe="FÃ©minin" numero="clt1" idAgence="ag1">
			<raisonSociale>afcepf</raisonSociale>
			<compte numero="cpt_1_1">
				<!-- ceci est un commentaire -->
				<tauxInteret taux="0.05"/>
				<solde>25000</solde>
				<!-- encore un commentaire -->
				<dateOuverture>25/01/1992</dateOuverture>
			</compte>
			<compte numero="cpt_1_2">
				<solde>-250</solde>
				<dateOuverture>12/12/2001</dateOuverture>
			</compte>
			<adresse>
				<numero>3</numero>
				<voie>rue Danton</voie>
				<codePostal>92100</codePostal>
				<ville>Malakoff</ville>
			</adresse>
		</client>
		<client type="perso" numero="clt2" idAgence="ag1">
			<nom>benoit</nom>
			<prenom>chauvet</prenom>
			<compte numero="cpt_2_1">
				<solde>3</solde>
				<dateOuverture>25/01/2010</dateOuverture>
			</compte>
			<adresse>
				<numero>45</numero>
				<voie>rue Dumas</voie>
				<codePostal>93000</codePostal>
				<ville>Montreuil</ville>
			</adresse>
		</client>
	</clients>
	<agences>
		<agence id="ag1">
			<adresse>
				<numero>10</numero>
				<voie>rue du Midi</voie>
				<codePostal>94300</codePostal>
				<ville>Vincennes</ville>
			</adresse>
		</agence>
	</agences>
</banque>
